server:
  port: 8080
  servlet:
    context-path: /cbs
    session:
      persistent: true
      timeout: 10m
#  tomcat:
#    remoteip:
#      protocol-header: x-forwarded-proto

spring:
  application:
    name: service

  profiles:
    #active: @spring.profiles.active@ #replace
    default: @spring.profiles.default@ #dev

  output:
    ansi:
      enabled: ALWAYS

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/core?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: Rooteshwar@12

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
        #defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: off

    properties:
      hibernate:
        format_sql: true
        default_schema: core
        #transaction.jta.platform: changeIt
        #max_fetch_depth: 1

  liquibase:
    enabled: true
    #contexts: dev
    database-change-log-table: cbs_schema_history
    database-change-log-lock-table:  cbs_schema_lock
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    default-schema: core


#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql.bkp
#      schema-locations: classpath:schema.sql.bkp

# I can use P6Spy a jdbc proxy for other reasons.

  security:
    user:
      name: suraj
      password: suraj

logging:
  level:
    root: INFO

management:
  server:
    port: 7070 # access it with http://localhost:7000/actuator
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
#  info:
#    git:
#      enabled: true
#      mode: full

debug: false

info:
  app:
    name: core-backing-solution
    description: financial solution for banking
    version: 1.0.0

