server:
  port: 8080
  servlet:
    context-path: /cbs
    session:
      persistent: true
      timeout: 10m

spring:
  application:
    name: service

  profiles:
    #active: @spring.profiles.active@ #replace
    default: @spring.profiles.default@ #dev

  output:
    ansi:
      enabled: ALWAYS

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS core\;CREATE SCHEMA IF NOT EXISTS surface
    username: root
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    show-sql: off

    properties:
      hibernate:
        format_sql: true
        default_schema: core
  #        transaction.jta.platform: changeIt

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true

#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql.bkp
#      schema-locations: classpath:schema.sql.bkp

# I can use P6Spy a jdbc proxy for other reasons.

logging:
  level:
    root: INFO

management:
  server:
    port: 7070 #access it with http://localhost:7000/actuator
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized
